apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 2
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: clecio/products-store-mvc:1.0 # acrforaks2020.azurecr.io/webapp:1.0
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__ProductsContext
            #value: Server=mssql-service;Database=ProductsDB;User=SA;Password=@Aa123456;
            valueFrom:
              configMapKeyRef: 
                name: mssql-connection-configmap
                key: db-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100
  type: NodePort       
